# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 28d574fd03189dbc7884c3ceaf8150711f1b69c8d7bbf0ce1a413cef27302512621b85e7a521fca83474e55886b083ad059c8b9c49a736372abe9a9c88e314b6

test:
  secret_key_base: 79c81ab0cde48ebd61c563299c64085fd584acf1449a5f9b47ae5477b30c8cb51aae2facf159fec46bc1d064ea508fa742ca89dc33b413aabe4379529db7d5e0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
